version: "3"

services:
  app:
    build: 
      context : kfs
      dockerfile : Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host