name: Build

on:
  pull_request:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget tar xz-utils mtools xorriso build-essential grub2-common
        wget https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
        tar xf ./zig-linux-x86_64-0.12.0.tar.xz
        mv zig-linux-x86_64-0.12.0/* /bin

    - name: Building
      run: make

